name: dbe2-202602-app-mvc
services: 
  app_php:
    build:
      dockerfile: ./Dockerfile
      args:
          MYSQL_CLIENT: mariadb-client
      context: .
    command: > 
            sh -c "cd /var/www/html/ &&
                    composer i &&
                    composer run start;"
    ports:
      - ${APP_PORT:-8083}:80
    volumes:
        - '.:/var/www/html'
    networks:
      - app_net
    depends_on:
      - app_db
  app_db:
    image: 'mariadb:latest'
    ports:
        - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASS}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${DB_NAME}'
        MYSQL_USER: '${DB_USER}'
        MYSQL_PASSWORD: '${DB_PASS}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
        - 'vol_db:/var/lib/mysql'
    networks:
        - app_net
    healthcheck:
        test:
            - CMD
            - healthcheck.sh
            - '--connect'
            - '--innodb_initialized'
        retries: 3
        timeout: 5s
  phpmyadmin:
        image: 'phpmyadmin/phpmyadmin:latest'
        ports:
          - '${FORWARD_MYADMIN_PORT:-8093}:80'
        environment:
            PMA_HOST: 'app_db'
        networks:
            - app_net
        depends_on:
            - app_db
  pgsql:
        image: 'postgres:15'
        ports:
            - '${FORWARD_PG_PORT:-5433}:5432'
        environment:
            POSTGRES_DB: '${DB_NAME}'
            POSTGRES_USER: '${DB_USER}'
            POSTGRES_PASSWORD: '${DB_PASS}'
            POSTGRES_HOST_AUTH_METHOD: 'trust'
        volumes:
            - 'pgsql-data:/var/lib/postgresql/data'
            # - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - app_net
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_NAME}'
                - '-U'
                - '${DB_USER}'
            retries: 3
            timeout: 5s
  pgadmin:
        image: 'dpage/pgadmin4:latest'
        ports:
          - '${FORWARD_DBADMIN_PORT:-8090}:80'
        environment:
            PGADMIN_DEFAULT_EMAIL: 'admin@pgadmin.com'
            PGADMIN_DEFAULT_PASSWORD: 'admin'
        networks:
            - app_net
        depends_on:
            - pgsql
networks:
  app_net:
    ipam:
      config:
        - subnet: 10.255.0.0/24
    driver: bridge
volumes:
  vol_db:
    driver: local
  pgsql-data:
        driver: local